# Generated by Django 4.2.9 on 2024-07-03 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_matricula_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fechafin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fechaini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
